### ISSUE TITLE
Login failed with LmApiClient.auth.login

### ISSUE THREAD

**Issue by genlinjiao** [lifemapper/lm_client#31]
I am using Lifemapper_Client_Library and following the tutorial as the following:
>>> from lm_client.client.client import LmApiClient
>>> cl = LmApiClient()
>>> cl.auth.login('my_user', 'my_password')
And I got the following response:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-3bdd893c2722> in <module>
----> 1 cl.auth.login('genlin', 'gj196163')

~/projects/geodesign/env38/lib/python3.8/site-packages/lm_client/apis/auth.py in login(self, user_id, passwd)
     24             allowed_domains=(policy_server,))
     25         self.cookie_jar = cookie_jar.LWPCookieJar(policy=policy)
---> 26         opener = urllib2.build_opener(
     27             urllib2.HTTPCookieProcessor(self.cookie_jar))
     28         urllib2.install_opener(opener)

NameError: name 'urllib2' is not defined
Could someone help me with the issue?

**Comment by cjgrady** [comment]
Are you using python3?  This repo hasn't been updated for python3 yet.  It shouldn't take much work to do though

**Comment by cjgrady** [comment]
I've opened #32 for updating to python3.
